#!/usr/bin/perl
## Pombert Lab 2020
my $version = 0.1;
my $name = 'sanitize_pdb.pl';

use strict; use warnings; use Getopt::Long qw(GetOptions); use File::Basename;

## Usage definition
my $USAGE = <<"OPTIONS";
NAME		$name
VERSION		$version
SYNOPSIS	Cleans .pdb files genrated with trRosetta to remove non-standard PDB entries

COMMAND         $name -p PDB/*.pdb -o PDB_clean

OPTIONS:
-p (--pdb)      .pdb files generated by trRosetta
-o (--output)   Output folder
OPTIONS
die "\n$USAGE\n" unless @ARGV;

## Defining options
my @pdb;
my $out;
GetOptions(
    'p|pdb=s@{1,}' => \@pdb,
    'o|output=s' => \$out,
);

if (!defined $out){$out = './';}
unless (-d $out){mkdir $out;}

## cleaning up pdb files
while (my $pdb = shift@pdb){
    open PDB, "<", "$pdb";
    my($name, $dir) = fileparse($pdb);
    open CLEAN, ">", "$out/$name";
    my @tags = ('HEADER', 'EXPDTA', 'REMARK', 'ATOM', 'TER');
    while (my $line = <PDB>){
        chomp $line;
        foreach (@tags){
            if ($line =~ /^$_/){print CLEAN "$line\n";}
        }
    }
    close PDB; close CLEAN;
}